# Generated by Django 4.0.5 on 2022-08-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='date',
        ),
    ]
