# Generated by Django 4.0.5 on 2022-09-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_news', '0006_subscribersusers_alter_category_subscribers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(through='portal_news.PostCategory', to='portal_news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='post',
            name='select_choices',
            field=models.CharField(choices=[('AR', 'Статья'), ('NE', 'Новость')], default='AR', max_length=2),
        ),
    ]
