# Generated by Django 4.0.5 on 2022-10-04 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal_news', '0008_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
